### ISSUE TITLE
Custom TOC location

### ISSUE THREAD

**Issue by MaximeWillinger** [splitbrain/dokuwiki-plugin-dw2pdf#174]
Hi guys,

Is it possible to choose a custom TOC location in the Wiki page ?
For example, I would like to add a few pages before TOC. These pages should not be numbered.

Thanks,

**Comment by splitbrain** [comment]
I don't think that's supported by the mpdf library. But you could always do it in a post production step with some PDF rearranging tool.

**Comment by Klap-in** [comment]
You can define some snippets, that form the template of the generated pdf.
See https://www.dokuwiki.org/plugin:dw2pdf#pdf_templates

When you use the `cover.html` you can create with html one or more pages, that are added at the beginning of the file before the ToC.
Other possibilities aren't available due to the working of mPdf library.
