### ISSUE TITLE
PDFs are generated even for non-existing pages

### ISSUE THREAD

**Issue by xrat** [splitbrain/dokuwiki-plugin-dw2pdf#179]
The current version of the DW2PDF plugin offers and allows to create PDFs even from non-existing pages and/or non-permitted pages. An empty PDF is generated (besides the template). The log shows a warning:

```
[Mon Apr 06 22:36:40 2015] [error] [client (...)] PHP Warning:  
filemtime(): stat failed for (...)/pages/public/nothinghere.txt
in (...)/dw/lib/plugins/dw2pdf/action.php on line 492
```

DW2PDF should not be offered for non-existing pages. A `?do=export_pdf` should fail silently or return a proper error message.

**Comment by LarsGit223** [comment]
This should be quite easy for `?do=export_pdf`.
A single page shall be exported. So if an http error is returned the meaning is clear.

But what should be done for `?do=export_pdfbook` or `?do=export_pdfns`?
In that case multiple pages shall be exported but only some might be empty or not accessible. Shall the book/namespace be exported and jsut empty or inaccessible pages are left out without notice?
How can the export be delviered and the user being notified that some pages were not exported and why.

Maybe a intermediate page should be generated stating that not all pages were exported. At the end the page should contain a link to download the exported book/namespace.

Are there othe ideas/solutions?

**Comment by Klap-in** [comment]
At least not-existing pages should be skipped, without error/warnings/notices of PHP.

I don't know if I like setting a user message. Is a msg() displayed directly after a call to export?

For the bookcreator it should integrate with the bookmanager, no idea what is a nice manner to perform that. I guess it is already using msg()

**Comment by LarsGit223** [comment]
Well, bookcreator uses msg(). E.g. if you do not enter a title for the pdf/document then it complains with a msg() and underneath it shows the book export page (wiki:ebook).

But this is imple because both is XHTML, the page and the msg().

If a page is empty the scenario is slightly different:

- a user clicks the "Export" button to create the book
- a http request with `?do=export_pdf` is sent
- it is received and being processed by the dw2pdf plugin
- that responds to the request by sending a pdf file as result of the export
- Now, I can not simply call msg() to create a warning in the dw2pdf plugin. The msg() would be inserted in the pdf file stream and corrupt/damage the file.

Or is there a way to simply deliver the pdf file stream and the msg() at the same time?

**Comment by Klap-in** [comment]
When using ?do=export_pdf, it should not export a page, when the page doesn't exist. It should return to the page and use msg() for the message. Example of this way of error checking is in the function collectExportPages() in action.php as well.

**Comment by xrat** [comment]
Thanks all for your comments. @Klap-in thanks for pointing me at collectExportPages(). By adding `&& $INFO['exists']` there and in addbutton() I could at least protect my public wiki from bots. Fortunately, I have no links to `?do=export_pdfbook` or `?do=export_pdfns`. Clearly, this needs a proper fix.

**Comment by Klap-in** [comment]
Since #312 button is only shown for existing pages, and msg is given if page not exists.
