### ISSUE TITLE
Did not generate pdf from pages with issue tracker plugin.

### ISSUE THREAD

**Issue by dior1** [splitbrain/dokuwiki-plugin-dw2pdf#188]
When generating a pdf from an issue from the issue tracker plugin, the pdf is only generating the wiki Basic structure and nothing from the issue tracker page

**Comment by Klap-in** [comment]
What do you see at the print preview of your browser? Does it already contain the desired info? The lay-out of the printpreview is used as input for this plugin.

**Comment by dior1** [comment]
The browser print preview show the content of the issue tracker ticket basically correkt.

**Comment by Klap-in** [comment]
The issuetracker plugin uses several views (e.g. `&do=showcaselink`). The default action-url of the dw2pdf export is e.g. `http://examplewiki.com/test:issuetracker?do=export_pdf`. This use the do=show view, that is what just shows the article. 

If the debug configuration setting is (temporary) enabled, you can use: http://examplewiki.com/test:issuetracker?do=export_pdf&debughtml=text
This shows the html that is inputted into mPDF
And this http://examplewiki.com/test:issuetracker?do=export_pdf&debughtml=text renders it as html.

It appears it shows there relatively fine.
Maybe if it is feed into mPDF the inline javascript give troubles or makes that more stuff is hidden than intended..
Also has dw2pdf minimal style sheets included, so some other forms I saw broken styling. But not that the form was missing at all, like here.

Because there are that many details in this interface it is not doable for me to determine the cause of this hidden form. So far I now understand the issue, I expect that improving the stylesheets could do already a job. But that should be done in the issuetracker plugin.
