### ISSUE TITLE
Performance for large pages

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [splitbrain/dokuwiki-plugin-dw2pdf#189]
Hi,

when I want to export a quite long wiki page the php-limit of 30 seconds is often exceed when I turn on the toc option. The message is 

"Fatal error: Maximum execution time of 30 seconds exceeded in /opt/lampp/htdocs/wiki/lib/plugins/dw2pdf/mpdf/mpdf.php on line ..."

Without toc the exporting process succeeds within the 30s, and a pdf-file of ca. 65 pages is generated. What can I do to optimize the performance?

Regards 
Juergen

**Comment by Klap-in** [comment]
No idea. Because I have no idea which content you include in the pdf.
There is a new version of mPDF coming. Maybe(??) this provides a bit better performance as well?
You could eventually temporary test that branch.

Can you provide example content that demonstrates your issue? without realistic data it is difficult for us to test.

65 pages is not small. So with the application of a bit more complicated syntax, I can image it takes some time.

**Comment by Juergen-aus-Koeln** [comment]
Instead of this I would rather like to use the bookcreator plugin, because by reason of the different handling I would hope that there wouldn't be any performance problems. But the dw2pdf plugin generates the toc, and this is obligatory for me. I don't know how to implement this for the bookcreator. And therefore, currently my attempt was to load all subpages into one superior page by including them with the include plugin.

**Comment by Klap-in** [comment]
The bookcreator uses the exact same code.
Bookcreator is just a handy interface.

**Comment by Klap-in** [comment]
What do you mean with switching on the 'toc' option? How did you do that?

**Comment by Juergen-aus-Koeln** [comment]
With switching on the 'toc' option I mean using the url parameter toc=1

**Comment by Klap-in** [comment]
I guess that since PHP 7 the performance has improved. But further I don't have any suggestions.
On long term the mPDF library will be improved in general, I expect at performance level as well.
I close the issue because I don't have specific action points for it.
