### ISSUE TITLE
PHP Fatal Error on helper/config.php on line 569

### ISSUE THREAD

**Issue by dagobert** [splitbrain/dokuwiki-plugin-dw2pdf#211]
I newly installed this plugin. After that dokuwiki did not work any more. Apache weooro log says:

PHP Fatal error:  Can't use method return value in write context in /var/www/.../lib/plugins/odt/helper/config.php on line 569

The lines:
```
$template = $this->getParam ('template');
$odt_template = $this->getParam ('odt_template');
if (!empty($this->getParam ('template')) && empty($this->getParam ('odt_template'))) {
     $this->setParam ('odt_template', $this->getParam ('template'));
}
```

It seem that you already prepared for fixing this problem but did not complete the fix. After changing the lines above to the following, everything works like a charm:

```
$template = $this->getParam ('template');
$odt_template = $this->getParam ('odt_template');
if (!empty($template) && empty($odt_template)) {
    $this->setParam ('odt_template', $this->getParam ('template'));
}

```

**Comment by Klap-in** [comment]
You write: `/var/www/.../lib/plugins/odt/helper/config.php on line 569`
I think you mixed the issue trackers of the dw2pdf plugin and the ODT plugin. 

Looking at the code of the ODT plugin, it seems that the issue was catched recently: https://github.com/LarsGit223/dokuwiki-plugin-odt/blob/master/helper/config.php

See here for further info/conversation: https://github.com/LarsGit223/dokuwiki-plugin-odt/pull/88
