### ISSUE TITLE
usestyle ignores style

### ISSUE THREAD

**Issue by coastgnu** [splitbrain/dokuwiki-plugin-dw2pdf#212]
Moin Andi, moin Gerrit

It seems that some print styles are ignored by dw2pdf

In Dokuwiki configuration I set 
`plugin»dw2pdf»usestyles` to `pagequery,pagelist,inlinetoc,wrap` but the inlinetoc style never was used.

I changed `conf/all.css` which now has the css-styles of `inlinetoc/print.css`. 
When printing from Firefox with "Print to pdf" the inlinetoc gets printed as a charm.
When using dw2pdf the inlinetoc css is ignored as before.

In  `plugin/inlinetoc` I linked `style.css` to `all.css`, nothing changed, dw2pdf doesn't care for the inlinetoc css styles.

Is this a feature, a bug or did i miss something??

regards,
thomas

**Comment by Klap-in** [comment]
The `ustesyles` config setting is working.
The reading order of all.css and style.css were swapped, but that should not influence, I guess, your test results.

The inline TOC did, at least in last version of dw2pdf, not appear, because the rendering for dw2pdf has some custom functions. These customized functions did not store the ToC items. So at moment of export no ToC was available. Fixes are proposed.
