### ISSUE TITLE
PDF export is OK, However usually extremely slow

### ISSUE THREAD

**Issue by billzt** [splitbrain/dokuwiki-plugin-dw2pdf#227]
I installed the latest stable version of Dokuwiki and the master version of dw2pdf. All options in dw2pdf are default. The PDF export is OK, however usually extremely slow, even though the page is very small. It usually takes >1 minutes. (The server is in the intranet, most operation would finished in several miliseconds).

Some times it even show php error as:
`http://192.168.7.11/private/labwiki/wiki/syntax?do=export_pdf`
![qq 20160301084953](https://cloud.githubusercontent.com/assets/1146090/13414064/9753a028-df8a-11e5-820b-d9c6b38dad9e.png)

Is there any other configureations I should change?

**Comment by flohmueller** [comment]
One possibility might be to switch off qrcodes by setting "admin / configuration / plugin»dw2pdf»qrcodesize" to an empty value.

qrcode generation is delegated to an external url (https://chart.googleapis.com/). If that's unreachable... waiting for a timeout might cause your delays. Especially when using bookcreator to create "books" of several wiki pages, each one with it's own qrcode + timeout.

And since you're running a server in the intranet, maybe it's internet access might be a little..restricted!? ;)

**Comment by billzt** [comment]
Thank you. After I switch off qrcodes, PDF export is now OK and relatively fast.
