### ISSUE TITLE
Last modified timestamp does not reflect timezone offset

### ISSUE THREAD

**Issue by issmirnov** [splitbrain/dokuwiki-plugin-dw2pdf#239]
Hi,

I'm running the latest version of Dokuwiki, with Lotar's Bootstrap 3 theme. I made an export of a page on my wiki and noticed that the "last modified" timestamp seems to be GMT. 

Is this a quick fix?

**Comment by dougti** [comment]
The author has used the [gmdate()](http://php.net/manual/en/function.gmdate.php) function, instead of the [date()](http://php.net/manual/en/function.date.php) function, which returns the time in GMT/UTC. They've also hard-coded the string "GMT" into the headers.

> root@portal:/var/www/html/wiki/lib/plugins/dw2pdf# egrep -irn "(gmdate|GMT)" .
> ./mpdf/includes/out.php:17:                             header('Expires: Sat, 26 Jul 1997 05:00:00 GMT');
> ./mpdf/includes/out.php:18:                             header('Last-Modified: '.gmdate('D, d M Y H:i:s').' GMT');
> ./mpdf/includes/out.php:29:                     header('Expires: Sat, 26 Jul 1997 05:00:00 GMT');
> ./mpdf/includes/out.php:30:                     header('Last-Modified: '.gmdate('D, d M Y H:i:s').' GMT');
> ./mpdf/mpdf.php:8307:                           header('Expires: Sat, 26 Jul 1997 05:00:00 GMT');
> ./mpdf/mpdf.php:8308:                           header('Last-Modified: '.gmdate('D, d M Y H:i:s').' GMT');
> ./mpdf/mpdf.php:8320:                   header('Expires: Sat, 26 Jul 1997 05:00:00 GMT');
> ./mpdf/mpdf.php:8321:                   header('Last-Modified: '.gmdate('D, d M Y H:i:s').' GMT');

I replaced `gmdate` with `date` & `GMT` with my own timezone.

**Comment by Klap-in** [comment]
the mPDF library has been updated. It sets a timezone by itself, overwriting current settings.
Last release has improved this.

So far I have seen the export via dw2pdf doesn't touch the `header(..)` lines you list here, but uses the DokuWiki's http client code.

So I expect this issue is solved by the improvements of mPDF.
