### ISSUE TITLE
Additional PDF template replacements

### ISSUE THREAD

**Issue by rthill** [splitbrain/dokuwiki-plugin-dw2pdf#242]
I would like to use additional template tags in my pdf exports. Those tags include:
- Author
- Username
- Email

It would be great if all of the template tags from https://www.dokuwiki.org/namespace_templates would be accepted by DW2PDF.

**Comment by Klap-in** [comment]
Note that these can be only used in the headers, footers and citation box.
Otherwise you get at the page plain `@USER@`, `@NAME@` and `@MAIL@` placeholders. (I think it is not the purpose of dw2pdf plugin to offer such replacements in the wiki article itself)

The literal meaning of the placehoders for namespace templates are:
@USER@ -  ID of user who is creating the page
@NAME@ - name of user who is creating the page
@MAIL@ - mail address of user who is creating the page

Do you propose to let it replace by the properties of the page creator. I think that will not have much use. Or by last author? So far I don't get your usage of this feature. So could you please elaborate?

**Comment by Klap-in** [comment]
Any one interested in the following placeholders?
@creator_user@
@creator_name@
@creator_mail@

https://www.dokuwiki.org/plugin:dw2pdf:pdftemplate

**Comment by splitbrain** [comment]
I don't think they are really needed. It's the last editor that should vouch for a page's content.

**Comment by Klap-in** [comment]
For myself I do not see significant use of @creator_user@, @creator_name@, @creator_mail@ or @modifier_user@, @modifier_name@, @modifier_mail@ (or something like these..) So I go for closing this.
