### ISSUE TITLE
images not showing in PDFs (dw2pdf 2017-06-27)

### ISSUE THREAD

**Issue by root555** [splitbrain/dokuwiki-plugin-dw2pdf#286]
After updating to the new version the resulting pdf contains a small rectangle with red x inside instead of every image. php7-gd is installed and I have the same behavior with png, jpg and bmp.
The previous version is working without any problems.

Update:
- I have verified, that there are no errors in apache logfile, while converting to pdf file, and the pdf documents are not cached.
- I have the same problem on following systems:
openSUSE 42.2 (x86_64), Apache/2.4.23, PHP 7.0.7
Raspbian GNU/Linux 8 (jessie), Apache/2.4.10, PHP 5.6.30-0+deb8u1

**Comment by riess82** [comment]
I have the same problem.
I have traced it to img src="..." containing &amp; which should be &

**Comment by whnr** [comment]
Same here. After the update all images fail. Emoticons work now (at least the standard happy face) wich they didn't before for me.

**Comment by pashol** [comment]
same issue

Windows IIS/FastCGI with PHP 5.6.31, GD enabled
Type of image doesn't matter.

**Comment by showmetheworld** [comment]
okay, it IS a permission Problem.
If you comment out Permission checking in DokuPDF.class.php Lines 127 - 128 it is working.
That would be a very ugly hack and no good idea on production Server...

**Comment by showmetheworld** [comment]
Here we go. After debugging around, the main problem is, that the DokuPDF.class.php is not extending the _getImage class from mpdf anymore.
The underlaying problem is a lot more complex than I hoped and for now I don't have a solutions which not includes editing mpdf files - which means updating will be a problem.
I asked on [stack overflow](https://stackoverflow.com/questions/45533974/overwrite-a-function-in-a-class-called-by-another-class) where you can see the underlaying problem: mpdf has moved the getImage function in a nother class which is called by mpdf.php and stored in a private var.

What you can do to get it work for now is copy the content of the function _getImage in DokuPDF.class.php from Line 87 starting with `global ...`  to Line 149, just **before** `return ...` and place it in  dw2pdf/vendor/mpdf/mpdf/src/Image/ImageProcessor.php at the very beginning of the function `getImage` at Line 114, so that the needed Dokuwiki code is running **before** the mpdf getImage code.

**Warning**: this is very hacky and the next update will overwrite the code and breaks your pics again!

**Comment by riess82** [comment]
showmetheworld: Thank you for your detective work and the hack provided. Works like a charm.
