### ISSUE TITLE
Update or install error

### ISSUE THREAD

**Issue by noelspringer** [splitbrain/dokuwiki-plugin-dw2pdf#305]
When attempting an update the following error is reported:

`Parse error: syntax error, unexpected '[' in /home/user/www/wiki/lib/plugins/dw2pdf/action.php on line 889`

This error then appears on every page making the site unavailable. If the plugin is deleted from the `/lib/plugins` directory and installed from the Admin Extension manager, the same issue occurs.

**Comment by KaySoftDe** [comment]
I experience the same issue. I needed to commend out the `public function addsvgbutton(Doku_Event $event)` function at the action.php in order to recover my wiki.
but sure the dw2pdf plugin is no more working.

**Comment by Klap-in** [comment]
What are your PHP versions?

**Comment by Klap-in** [comment]
The mPDF library version 7.0 is used in the last version of dw2pdf plugin and this version requires at least PHP 5.6. 

I guess that this syntax error is indeed due to older version of PHP as well. 
Please upgrade your PHP to a recent version. Older PHP versions also doesn't receive (security) updates anymore...

**Comment by noelspringer** [comment]
OK you are right, I have an older version of PHP on this particular server. Thanks! Time to undertake the overdue upgrade.
