### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by punk-t** [splitbrain/dokuwiki-plugin-dw2pdf#306]
After upgrading this plugin I got an HTTP500.

Remembering an older issue with the Title Plugin [(see here)](https://github.com/ssahara/dw-plugin-pagetitle/issues/8) I tested several PHP versions. My default PHP5.3 causes the error, PHP5.4 and higher versions don't.

**Comment by Klap-in** [comment]
This plugin needs at least PHP 5.6, because it uses some recent syntaxes and a library that needs PHP 5.6 or recenter.

Please upgrade your PHP to a recent version. Older PHP versions also doesn't receive (security) updates anymore...

**Comment by bby-bishopclark** [comment]
> This plugin needs at least PHP 5.6, because it uses some recent syntaxes and a library that needs PHP 5.6 or recenter.
> 
>  Older PHP versions also doesn't receive (security) updates anymore...

That's weird, then:  https://access.redhat.com/errata/RHSA-2020:2835  and of course http://mirror.centos.org/centos/7.9.2009/os/x86_64/Packages/php-5.4.16-48.el7.x86_64.rpm and https://scientificlinux.org/category/sl-errata/slsa-20201112-1/ and https://linux.oracle.com/errata/ELSA-2020-1112.html 

Did you know that Enterprise Linux vendors branch a project and commit to security updates for up to 10 years?  It's a huge factor in Enterprise Linux's appeal for a lot of organized development looking for a stable dev base or certification.

**Comment by Klap-in** [comment]
Quote from https://www.php.net/supported-versions.php:  "End of life | A release that is no longer supported. Users of this release should upgrade as soon as possible, as they may be exposed to unpatched security vulnerabilities."

So not so helpful for your kind of application... I think that in general most web software as Dokuwiki is not providing support for such old versions too long. 10 years is really long. But any help is welcome!

**Comment by bby-bishopclark** [comment]
> Quote from https://www.php.net/supported-versions.php: "End of life

The OEM gave up, and that's understood.  Boredom happens all the time, and that's why enterprise vendors fork the ephemeral OEM code and maintain their branch.  It's evident in the numbering.

The notion that the OEM discarding their own work means no more security updates is a really irresponsible idea to be spreading. Enterprise OS distributors already have a hard time trying to explain it, and this isn't helping.

10 years in the Enterprise space is nothing more than an agreed window before revenue against costs becomes challenging; but that's nothing you need to concern yourself with.

**Comment by Klap-in** [comment]
I see.
