### ISSUE TITLE
support plugin nodisp with ACL depending rules

### ISSUE THREAD

**Issue by trcrem** [splitbrain/dokuwiki-plugin-dw2pdf#409]
Hello,
generating pdf-files ignores the acl-based tags of nodisp plugin. Example: a part tagged like `<nodisp 2>FIXME</nodisp>` shows `FIXME` in browser only if user has logged in. If the same user generates a pdf, the FIXME will be generated in the file. By this there is no accountlevel wich can prevent useraccess to excluded content, if pdf output is activated in dokuwiki.  The content of pdf is not the same like the view of the website for user that is not logged in. -> pdf as _a_ backdoor to restricted contents

I'm not shure, if dw2pdf ignores the ACL at all or if it only ignores the tags of include plugin.

Suggestions: 

1.   include a parameter for ACL in general for the use of PDF-button in dokuwiki. So it will depend on login and the permission of the user, wich pages and contents of each page will be generated regarding the accountlevel of the user.
2.  include this as a parameter for bookcreator-plugin. By this a pdf /a book could be created by admin with contents for quality or control of progress or otherwise for customer withput internal contents.
![dw content online versus pdf](https://user-images.githubusercontent.com/69630759/90133120-3cd63100-dd6f-11ea-888d-0a7238ee6d36.png)

**Comment by Klap-in** [comment]
Eh, I guess the nodisp plugin is just hiding info but not really removing it. So I guess now that by looking to the source of a wiki page everybody can see the content.
https://github.com/turnermm/nodisp/blob/3a687bb6cfe4251fb2d2f74ea49793af64559d1b/syntax.php#L57

Dw2pdf normally just export the wiki article as bare html, with minimal css styles. Sometimes this is not enough styling to let a plugin work properly. But in this case a simple element style is applied, so I would expect it could work.. but maybe some extra dw2pdf specific styling is needed.

ah.. I got the issue. This function removes all pieces that should be really removed for the reader somewhere on the end in an separate step. But it only runs if the wiki is displayed normally. The export to pdf is retrieved by a bit different route, so it seems it does not pass this cleanup step on the end.

**Comment by Klap-in** [comment]
Not sure if this needs attention from nodisp or dw2pdf plugin.

**Comment by trcrem** [comment]
Hi, thank you for the examination. I assume it's a result of dw2pdf plugin then, as this plugin choses probably a special way to cellect it's data ignoring the information of nodisp-tag. I'll refer to an issue to this plugin then, but will insert the information about a solution then in here, too. 
Thanks a lot

**Comment by digitalmouse** [comment]
To-date, I see this issue is still relevant.  When generating a PDF with dw2pdf,  <nodisp 2> blah </nodisp> content is still shown in the rendered PDF, even if not displayed in the browser.

That makes me think that the <nodisp> tags are ignored by this plugin.   The page is generated from the stored data (where the tags are), not the web-rendered page.

**Comment by splitbrain** [comment]
This should definitively be handled in the nodisp plugin.

**Comment by digitalmouse** [comment]
> This should definitively be handled in the nodisp plugin.

How so? The nodisp tags are embedded in the stored content.  They are not 'active' like a watching function.  The tags themselves can't see or know when the dw2pdf extension is generating a PDF.

Most likely the dw2pdf is stripping out any tags it does not recognize - such as the <nodisp> tag - when creating a PDF.  

Either the dw2pdf needs to be 'taught' the <nodisp> tag and respect it's ACL rules, or dw2pdf should 'call' the nodisp function somehow (if exists) just prior to rendering the PDF so that the resulting input to dw2pdf does not contain the hidden content.

**Comment by Klap-in** [comment]
dw2pdf plugin uses the xhtml rendering, and combined this default with the print css styles (which removes e.g. webpage headers and footers). A plugin could manipulate the html by adding a specific html output for that plugin for dw2pdf or specific pdf css styles)

See for details https://www.dokuwiki.org/plugin:dw2pdf:exportsupport
