### ISSUE TITLE
bug (semi-solved): PDF creation hangs

### ISSUE THREAD

**Issue by bomhard** [splitbrain/dokuwiki-plugin-dw2pdf#483]
Debian 11, actual DokuWiki and plugin. Some time ago dw2pdf stopped working. The ccalling URL was displayed and an error was written to apache2 error.log stating that 'dokuwiki\cache\cache\ doesn't exist.

commenting out 

dokuwiki\Cache\Cache;

in plugins/dw2pdf/action.php solves the issue, but I am not sure if that is a solution :)

**Comment by Klap-in** [comment]
No idea yet. Which DokuWiki version are you using?

**Comment by bomhard** [comment]
We are running actual Debian Bullseye (11.6) and Dokuwiki 0.0.20180422.a-2.1

DokuWiki says it is release 2018-04-22a "Greebo"

There is a newer version from backports I might install: 0.0.20200729-0.1~bpo11+1

This very likely is still outdated, but we have reasons to stay with Debian Stable. I just found out how to solve that probem and wanted to share. If this is rather a Debian problem than DokuWiki's I am sorry and fine to close the issue.

**Comment by Klap-in** [comment]
Due to the varying maintenance effort on these DokuWiki packages combined with an atypical folder structure, which results unfortunately in quite some confusion for some users, we recommend indeed to install DokuWiki directly and not from the Debian repositories. (That is also what we do ourselves at dokuwiki.org.)

If you use these older versions of DokuWiki, please realize that regularly these are not supported by recent updated plugins anymore. In these cases, please refer back to an older version of a plugin.

**Comment by bomhard** [comment]
Technically I agree but installing from Deebian Repo means it is accepted by BSI as part of the distribution. No additional validation and testing in GDPR sensitive environments. The Debian specific folder structure is no problem for me.

Dw2pdf supports Greebo so there should not be any problem.

**Comment by Klap-in** [comment]
Closing as I understand it now as mismatch between versions.
