### ISSUE TITLE
Error: Class "Mpdf\Mpdf" not found

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [splitbrain/dokuwiki-plugin-dw2pdf#496]
Hi together,

since the update of the dw2pdf plugin yesterday I get the following error message when I want to export a pdf file:
Error: Class "Mpdf\Mpdf" not found
Does anyone have an idea to solve this?

Best regards
Juergen

**Comment by spricer** [comment]
In what release this was fixed?
I am using splitbrain-dokuwiki-plugin-dw2pdf-2023-09-15-0-ge731542.tar.gz and still getting this error...
ENV:
Ubuntu 22.04.3 LTS (kernel 5.15.0-78)
PHP: 8.1.2-1ubuntu2.14

**Comment by spricer** [comment]
Downloading plugin from git directly fixed issue.
From dokuwiki plugin page only **splitbrain-dokuwiki-plugin-dw2pdf-2023-09-15-0-ge731542.tar.gz** is available..

**Comment by Klap-in** [comment]
It is for me still unclear how you can find a link pointing to 'splitbrain-dokuwiki-plugin-dw2pdf-2023-09-15-0-ge731542.tar.gz', as the wiki pages points to https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/tarball/master, which should retrieve the latest code on GitHub.

**Comment by spricer** [comment]
Have you tried clicking on above link?

**Comment by Klap-in** [comment]
> Have you tried clicking on above link and seeing actual file downloaded ?

I did not indeed. I see now what you mean (splitbrain-dokuwiki-plugin-dw2pdf-2023-09-15-0-ge731542.tar.gz as well). But, looking in the tar.gz I can find the needed fix...
This the fix for this issue:
https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/commit/d97a751ef5f1360cd4d5e5570eccc32548e668b8

If I download via https://github.com/splitbrain/dokuwiki-plugin-dw2pdf/archive/refs/heads/master.zip I get the same code. 
However, there is one difference, the tar uses an extra folder. Not tested if that makes a difference for the extension manager.

**Comment by spricer** [comment]
I have to install plugins manually as setup is in closed env. Copying splitbrain-dokuwiki-plugin-dw2pdf-2023-09-15-0-ge731542.tar.gz over existing plugin for some reason did not work. Direct  github download package worked fine. Did not go into details. Folder were copied 1:1 (not folder within folder).
